#include "sub_screens.h"

#include <gui/elements.h>

/* generated by fbt from .png files in images folder */
#include <ldtoypad_icons.h>

#ifndef LDTOYPAD_UI_TEXT
#ifdef MOMENTUM_UI_LANG_ZH_CN
#define LDTOYPAD_UI_TEXT(en, zh) (zh)
#else
#define LDTOYPAD_UI_TEXT(en, zh) (en)
#endif
#endif

void draw_placement_selection_screen(Canvas* canvas, SelectionType selection) {
    canvas_clear(canvas);
    canvas_set_font(canvas, FontPrimary);
    canvas_set_color(canvas, ColorBlack);

    canvas_draw_str(canvas, 10, 14, LDTOYPAD_UI_TEXT("Select a type to place", "选择放置类型"));

    char message[15] = {0};

    // Minifigure
    if(selection == SelectionMinifigure) {
        canvas_draw_icon(canvas, 6, 23, &I_minifig_selected);
        strcpy(message, LDTOYPAD_UI_TEXT("Minifigure", "人仔"));
    } else {
        canvas_draw_icon(canvas, 6, 23, &I_box_longer);
        canvas_draw_icon(canvas, 18, 25, &I_head);
    }

    // Vehicle
    if(selection == SelectionVehicle) {
        canvas_draw_icon(canvas, 44, 23, &I_car_bigger_selected);
        strcpy(message, LDTOYPAD_UI_TEXT("Vehicle", "载具"));
    } else {
        canvas_draw_icon(canvas, 44, 23, &I_box_longer);
        canvas_draw_icon(canvas, 49, 26, &I_car_bigger);
    }

    // Favorites
    if(selection == SelectionFavorites) {
        canvas_draw_icon(canvas, 82, 23, &I_star_selected);
        strcpy(message, LDTOYPAD_UI_TEXT("Favorites", "收藏"));
    } else {
        canvas_draw_icon(canvas, 82, 23, &I_star);
    }

    // Saved
    if(selection == SelectionSaved) {
        canvas_draw_icon(canvas, 104, 23, &I_save_selected);
        strcpy(message, LDTOYPAD_UI_TEXT("Saved", "已保存"));
    } else {
        canvas_draw_icon(canvas, 104, 23, &I_save);
    }

    canvas_draw_str_aligned(canvas, 64, 57, AlignCenter, AlignBottom, message);
}
